lib/testLauncher/SuitestLauncher.js
lib/testLauncher/commands/automated.js
lib/utils/Queue.js
lib/utils/testLauncherHelper.js
test/testLauncher/SuitestLauncher.test.js
test/utils/testLauncherHelper.test.js

Fixed typos for: followChildProcess, runAutomatedSession

SUIT-8986 Concurrency property with 0 doesn't work.

---

test/testLauncher/SuitestLauncher.test.js

currently we do not call closeSession in runAutomatedSession

SUIT-9012 Fix Unit Tests on JS API

---

demo/test/dummy.test.js
index.d.ts
lib/commands/startTest.js
lib/validataion/jsonSchemas.js
test/commands/startTest.test.js
test/context/authContext.test.js
yarn.lock

Updated startTest command. clientTestId should be mandatory and name should become optional.

SUIT-9121 Update startTest command

---

lib/testLauncher/SuitestLauncher.js
lib/testLauncher/launcherLogger.js
lib/utils/AuthContext.js
lib/utils/testHelpers/testLauncherTest.js
lib/utils/testLauncherHelper.js
test/testLauncher/SuitestLauncher.test.js
test/utils/testLauncherHelper.test.js

SUIT-9197 Add device name to JS API Test Launcher output

SUIT-9197 Add device name to JS API Test Launcher output

---

lib/chains/elementChain.js

SUIT-9293
Index property of element selector get's ignored when used with JS API

SUIT-9293 Index property of element selector get's ignored when used with JS API

---

lib/composers/intervalComposer.js
lib/composers/notComposer.js
lib/composers/repeatComposer.js
test/chains/cookieChain.test.js
test/chains/elementChain.test.js
test/chains/javascriptExpressionChain.test.js
test/chains/locationChain.test.js
test/chains/videoChain.test.js
test/composers/notComposer.test.js
typeDefinition/ElementChain.d.ts
typeDefinition/modifiers.d.ts
typeDefinition/suitest-tests.ts

SUIT-9273
Add "isNot" alias for not chain link

SUIT-9273 Add "isNot" alias for not chain link

---

lib/testLauncher/buildArgs.js

remove --logDir from suitest help

SUIT-9746 remove --logDir from suitest help

---

lib/texts.js
test/utils/SuitestError.test.js

Update unknownError text to satisfy new config name

SUIT-9748 Update unknownError text to satisfy new config name

---

lib/validataion/jsonSchemas.js
lib/validataion/validators.js

* add validation for addition properties
* add proper error message for additional properties

SUIT-9856 Add illegal element selector validation to js api

---

index.d.ts

according to index.d.ts setAppConfig accepts only one argument

SUIT-9858 according to index.d.ts setAppConfig accepts only one argument

---

lib/testLauncher/SuitestLauncher.js
lib/testLauncher/launcherLogger.js
test/testLauncher/SuitestLauncher.test.js

SUIT-9770 Display device name in interactive mode
Should wait for BE subtask.

SUIT-9754 / SUIT-9770 Display device name in interactive mode

---

lib/texts.js
lib/utils/socketErrorMessages.js
test/utils/socketErrorMessages.test.js

Improve networkRequest error description (actual / expected values)

SUIT-9670 Improve networkRequest error description

---

lib/utils/socketErrorMessages.js
test/utils/socketErrorMessages.test.js

Update jsExpressionError error handling to make it compatible with network API

SUIT-10063 Update jsExpressionError

---

.codeclimate.yml
README.md

After this merge we'll start to respect what CodeClimate suggest and will no longer merge PRs if CodeClimate maintainability decreases with your changes.

SUIT-10092 - Add CodeClimate badges to JS API repo

---

lib/constants/vrc.js
lib/mappings.js
typeDefinition/constants/Vrc.d.ts

SUIT-10154 Update roku vrc

---

index.d.ts
testDefinition/examplesTS/elementChain.ts

Element chain can accept string as an argument

SUIT-10218 Element chain can accept string as an argument

---

lib/texts.js
lib/utils/socketErrorMessages.js
test/utils/socketErrorMessages.test.js

Added handling for xbox 'You have to sign in to launch an app.'  error.

SUIT-10263 Add signInRequired error handling

---

lib/texts.js

Update wording for message when we detect that newer version of Suitest JS API is available.

Minor wording update

---

lib/utils/socketChainHelper.js
test/utils/socketChainHelper.test.js

Treat test line result with status warning as non error.

SUIT-10291 Handle test line warnings

---

config/index.js
lib/constants/timestamp.js
lib/testLauncher/commands/automated.js
lib/testLauncher/commands/common.js
lib/testLauncher/commands/interactive.js
lib/texts.js
lib/utils/common.js
lib/utils/logger.js
lib/validataion/jsonSchemas.js
test/utils/common.test.js

Made timestamp configurable with CLI args or RC file

SUIT-10354 Make timestamp in logs configurable with cli or rc file

---

lib/utils/SuitestError.js
lib/utils/envHelper.js
lib/utils/testLauncherHelper.js
test/utils/testLauncherHelper.test.js

SUIT-10399 Errors thrown by calling SuitestError exit method displays without colors

SUIT-10399 Errors thrown by calling SuitestError exit method displays without colors

---

lib/composers/requestMatchesComposer.js
lib/composers/responseMatchesComposer.js
testDefinition/definition.test.js
testDefinition/examplesTS/networkRequestChain.fail.ts
testDefinition/examplesTS/networkRequestChain.ts
typeDefinition/NetworkRequest.d.ts
typeDefinition/modifiers.d.ts
yarn.lock

Updated TypeDefinitions for networkRequest chain

SUIT-10380 Update networkRequest types

---

lib/chains/elementChain.js
test/chains/elementChain.test.js
testDefinition/definition.test.js
testDefinition/examplesTS/elementChain.fail.ts
testDefinition/examplesTS/elementChain.ts
testDefinition/examplesTS/suitest-tests.ts
typeDefinition/ElementChain.d.ts

SUIT-10352 Inconsistent doesNot

---

yarn.lock

added timestamp to yarn.lock

---

index.js

Possible fix, but I did not test it on windows.

SUIT-10282 Add windows process shutdown workaround

---

package.json
yarn.lock

Added husky hooks
- pre-commit - lint code
- pre-push - lint and test

SUIT-10861 Add husky hooks

---

lib/chains/networkRequestChain.js
test/chains/networkRequestChain.test.js

Drop Symbols and Symbol mapping from JS API

SUIT-10210 Drop Symbols and Symbol mapping from JS API

---

index.d.ts
test/composers/matchComposer.test.js
testDefinition/examplesTS/elementChain.ts

Fixed assert.element TS definition, so it can take string as an argument.

SUIT-9290 Fix assert element string param

---

lib/texts.js
lib/utils/socketErrorMessages.js
test/utils/socketErrorMessages.test.js

* SUIT-9951 Add xcode error handlers
* Update messages

SUIT-9951 Add xcode error handlers (#138)

---

lib/chains/elementChain.js
lib/composers/index.js
lib/composers/visibleComposer.js
lib/constants/comparator.js
lib/constants/composer.js
lib/texts.js
test/chains/elementChain.test.js
test/chains/videoChain.test.js
test/composers/visibleComposer.test.js
testDefinition/definition.test.js
testDefinition/examplesTS/elementChain.fail.ts
testDefinition/examplesTS/elementChain.ts
testDefinition/examplesTS/videoChain.ts
typeDefinition/ElementChain.d.ts
typeDefinition/modifiers.d.ts

Implement "element visible" on JS API

SUIT-11350 Implement "element visible" on JS API

---

lib/constants/element.js
lib/validataion/elementPropTypes.js
test/chains/elementChain.test.js
test/composers/matchComposer.test.js
testDefinition/examplesTS/elementChain.ts
typeDefinition/constants/Element.d.ts
typeDefinition/constants/ElementProps.d.ts

new property 'url' (PROP. WEB_VIEW_URL) was added to element

SUIT-11385 [JS API] Implement new property "url"

---

lib/texts.js
test/chains/elementChain.test.js

SUIT-11411 Rephrase set text on element to set text for element

---

lib/chains/elementChain.js
test/chains/elementChain.test.js
testDefinition/definition.test.js
testDefinition/examplesTS/elementChain.fail.ts
testDefinition/examplesTS/elementChain.ts
typeDefinition/ElementChain.d.ts

Update setText element chain. interval, count, until, timeout modifiers are not available with setText.

SUIT-11411 Update setText element chain modifier

---

lib/texts.js
lib/utils/socketChainHelper.js
lib/utils/socketErrorMessages.js
test/utils/socketChainHelper.test.js
test/utils/socketErrorMessages.test.js

Add error description when application is not running.

SUIT-11598 Add appNotRunning error message

---

lib/chains/pressButtonChain.js
lib/utils/socketErrorMessages.js
test/utils/socketErrorMessages.test.js

Fix apiId in invalidRepositoryReference error messages

SUIT-11647 Fix apiId selector in invalidRepositoryReference error

---

lib/chains/elementChain.js
lib/composers/index.js
lib/composers/videoComposers.js
test/chains/elementChain.test.js
test/chains/videoChain.test.js
test/composers/videoComposers.test.js
testDefinition/examplesTS/elementChain.ts
testDefinition/examplesTS/videoChain.ts
typeDefinition/ElementChain.d.ts
typeDefinition/VideoChain.d.ts
typeDefinition/modifiers.d.ts

Add syntax sugar for video chain subject

SUIT-9275 Add syntax sugar for video chain subject

---

index.js
lib/testLauncher/ipc/client.js

Another windows fix, we tested this on machine that failed.

SUIT-11910 Add socket.destroy when closing client

---

lib/api/request.js
lib/commands/startTestPack.js
lib/texts.js
test/commands/startTestPack.test.js

Added better error message for testPackGenTokens 404 response.

SUIT-12085 Add better error message when test pack not found

---

lib/testLauncher/SuitestLauncher.js
lib/testLauncher/processArgs.js
lib/utils/testLauncherHelper.js
lib/validataion/jsonSchemas.js
test/testLauncher/processArgs.test.js
test/utils/testLauncherHelper.test.js

Fix --inspect --inspectBrk in js api when used without port number

SUIT-12173 Fix --inspect --inspectBrk in js api when used without port number

---

testDefinition/examplesTS/elementChain.ts
typeDefinition/constants/VideoState.d.ts

SUIT-12371 Update tvOS video states enum

---

lib/api/webSockets.js
lib/utils/logger.js
lib/utils/stringUtils.js
test/utils/logger.test.js
test/utils/stringUtils.test.js

Display console output from the device.

SUIT-12786 Display console output from the device

---

testDefinition/examplesTS/elementChain.ts
typeDefinition/constants/VideoState.d.ts

SUIT-12371 (#196)

---

lib/chains/elementChain.js
lib/chains/videoChain.js
lib/commands/configure.js
lib/texts.js
lib/utils/chainUtils.js
test/chains/elementChain.test.js
test/chains/videoChain.test.js
testDefinition/examplesTS/videoChain.fail.ts
testDefinition/examplesTS/videoChain.ts
typeDefinition/VideoChain.d.ts

separate videChain from element chain

SUIT-13046 - Create own videoChain implementation js-api

---

lib/chains/playstationVideoChain.js
lib/chains/videoChain.js
test/chains/playstationVideoChain.test.js
test/chains/videoChain.test.js

SUIT-13296 Fix ps4 chain data json

---

lib/commands/startTestPack.js
lib/texts.js

SUIT-13238 - tokenUnauthorized error handling

SUIT-13238 - tokenUnauthorized error handling

---

lib/api/webSockets.js
lib/utils/common.js
lib/utils/interactiveProgressHanlder.js
lib/utils/translateResults.js
package.json
test/utils/translateResults.test.js
yarn.lock

Adjust markdown translation, update translation module.

Update translate module usage

---

lib/api/wsContentTypes.js
lib/composers/thenComposer.js
lib/utils/AuthContext.js
test/composers/thenComposer.test.js

Implement missing test chains request authentication based on current session.

SUIT-13322 Fix context auth for chains ws messages

---

lib/texts.js
lib/utils/socketErrorMessages.js
test/utils/socketErrorMessages.test.js

PR FYI
* SUIT-13482 - Translate new error codes (#242)

Release PlayStation 4 maintenance q4

---

index.d.ts
index.js
lib/chains/runTestChain.js
lib/texts.js
lib/utils/socketChainHelper.js
lib/utils/socketErrorMessages.js
test/chains/runTestChain.test.js
test/utils/socketErrorMessages.test.js
testDefinition/definition.test.js
testDefinition/examplesTS/runTestChain.fail.ts
testDefinition/examplesTS/runTestChain.ts
typeDefinition/RunTestChain.ts

* SUIT-13956 Add runTest chain
* SUIT-13956 Update runTest chain error message

Run test editor tests from JS API

---

lib/utils/socketErrorMessages.js
test/utils/socketErrorMessages.test.js

Show detailed Android adb error response to users.

SUIT-13174 Show adb response to users

---

lib/texts.js
lib/utils/socketErrorMessages.js
package.json
test/utils/socketErrorMessages.test.js
yarn.lock

Release apple configurator

---

lib/api/webSockets.js
lib/texts.js

Co-authored-by: andriichumak <andrey.c@mineus.net>

SUIT-15420 Added an error message for executorStopped event (#308)

---

package-lock.json
package.json

Updating @suitest/translate packages

fаeature/SUIT-16719 update package

---

index.d.ts
lib/commands/pairDevice.js
lib/commands/startRecording.js
lib/commands/stopRecording.js
test/commands/stopRecording.test.js

… startRecording, fix for pairDevice recording option

fаeature/SUIT-18496
